export const homeObjOne = {
  id: "about",
  lightBg: true,
  lightText: false,
  lightTextDesc: true,
  topLine: "Om Sprinto",
  headline: "Vi älskar teknik och avskyr dåliga lösningar.",
  description:
    "Vi startade Sprinto för att få utveckla tjänster som vi själva vill använda och som inte kräver en instruktionsbok för att förstå.Sprinto erbjuder ett roligare och friare arbete – en plats att utvecklas åt det håll man själv vill. Hos oss sitter ingen konsult på ”hyllan”. Jobbar man så jobbar man. Annars är man ledig. Då får man springa i skogen, cykla med cykelvagn eller snickra i snickarboden. Eller sitta för den delen, men bara om man själv vill!Vi gillar inte löneförhandlingar. Vår 80-20-modell gör att varje medarbetare kan styra över sin egen lön, tid och vilken utrusning eller utbildningar man vill gå på.",
  buttonLabel: "Skriv en rad",
  imgStart: false,
  img: require("../../images/programming.svg").default,
  //   img: require("../../images/programming.svg"),
  alt: "Car",
  dark: true,
  primary: true,
  darkText: true,
  fontBig: true,
  big: true,
}

export const homeObjTwo = {
  id: "focus",
  lightBg: false,
  lightText: false,
  lightTextDesc: true,
  topLine: "Om Sprinto",
  headline: "Vi älskar teknik och avskyr dåliga lösningar.",
  description:
    "Vi startade Sprinto för att få utveckla tjänster som vi själva vill använda och som inte kräver en instruktionsbok för att förstå.Sprinto erbjuder ett roligare och friare arbete – en plats att utvecklas åt det håll man själv vill. Hos oss sitter ingen konsult på ”hyllan”. Jobbar man så jobbar man. Annars är man ledig. Då får man springa i skogen, cykla med cykelvagn eller snickra i snickarboden. Eller sitta för den delen, men bara om man själv vill!Vi gillar inte löneförhandlingar. Vår 80-20-modell gör att varje medarbetare kan styra över sin egen lön, tid och vilken utrusning eller utbildningar man vill gå på.",
  buttonLabel: "Skriv en rad",
  imgStart: false,
  img: require("../../images/programming.svg").default,
  //   img: require("../../images/programming.svg"),
  alt: "Car",
  dark: true,
  primary: true,
  darkText: true,
  fontBig: true,
  big: true,
}
