export const employees = [{
        id: "1",
        img: require("../../images/jonatan.png").default,
        fullName: "Jonatan Hallenberg",
        title: "VD och utvecklare",
        description: "Jonatan är hjärnan bakom allt. I alla fall det som har med Sprinto att göra. Han är en sann fullstack-utvecklare med erfarenhet av att jobba med alltifrån startups till stora globala företag. Jonatan har ett förflutet som kapellmästare och besitter en unik förmåga att komma på idéer och kreativa lösningar. Han äter glass varje kväll men lyckas på något märkligt vis hålla sig i form ändå.",
    },
    {
        id: "2",
        img: require("../../images/profile.svg").default,
        fullName: "Jens Palmqvist",
        title: "Utvecklare",
        description: 'Jens lever efter devisen "Det måste finnas ett bättre sätt att göra det här på". Han är en fullstack-utvecklare som lutar kraftigt åt backend-hållet och älskar när något går sönder och måste fixas. Jens har en bakgrund som klassisk sångare och har från det med sig hur otroligt viktigt det är med samarbete och att lyfta varandra på arbetsplatsen. Han är inkapabel att köpa mindre än 500 gram lösgodis i taget.',
    },
    {
        id: "3",
        img: require("../../images/profile.svg").default,
        fullName: "Göran Kasholm",
        title: "Utvecklare",
        description: "Görans nisch är att vara bred. Han har erfarenhet av projektledning, kravanalys och lösningsdesign såväl som integration och automation. Göran är en glad och social person som är genuint intresserad av livets alla möjligheter. Han är noggrann och trivs i gränslandet mellan krav och lösning. Göran älskar att snickra och och spenderar gärna tid i skog och natur.",
    },
    {
        id: "4",
        img: require("../../images/profile.svg").default,
        fullName: "Carl-Johan Danver",
        title: "Utvecklare",
        description: "Carl-Johan är tekniskt lagd. Han har lång erfarenhet av att jobba med operations i banksektorn men även projektledning, kravanalys, integration och automation. Carl-Johan har mycket energi, är glad och social. Han tycker om att arbeta fram tekniskt snygga lösningar och procceser. Carl-Johan älskar extremsport, trivs i skogen och havet!",
    },
    {
        id: "5",
        img: require("../../images/profile.svg").default,
        fullName: "Fredrik Lindroth",
        title: "Utvecklare",
        description: "Fredrik gillar när saker och ting är invecklade. Han är fullstack-utvecklare med mycket erfarenhet av uppdrag inom områdena ekonomi och finans. Fredrik har stort tålamod och delar gärna med sig av sin kunskap till andra. Fredrik är en utpräglad nattuggla och en hejare på att köra truck.",
    },
    {
        id: "6",
        img: require("../../images/profile.svg").default,
        fullName: "Henning Bergström",
        title: "Utvecklare",
        description: "Henning gillar att gräva. Han är driftig och ger sig inte förrän har har hittat orsaken till ett problem. Henning har supermycket erfarenhet av backendutveckling på mjukvarubolag och är nu på jakt efter den perfekta användarupplevelsen i frontendens underbara värld. Han gillar hårdrock och missar aldrig en kopp kaffe.",
    },
]